services:
  backend:
    image: ghcr.io/anurik85/film-react-nest-backend:latest
    container_name: film-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: film-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: film-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: ghcr.io/anurik85/film-react-nest-nginx:latest
    container_name: film-nginx
    restart: unless-stopped
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - backend

  frontend-builder:
    image: ghcr.io/anurik85/film-react-nest-frontend:latest
    volumes:
      - react_build:/usr/share/nginx/html

volumes:
  pgdata:
  pgadmin-data:
  react_build:

networks:
  app-network:
    driver: bridge
