name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
env:
  GHCR_USERNAME: ${{ github.repository_owner | lower}}
  REPO_NAME: film-react-nest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Сборка и публикация образа Backend ---
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.REPO_NAME }}-backend:latest
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.REPO_NAME }}-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Сборка и публикация образа Nginx ---
      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.REPO_NAME }}-nginx:latest
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.REPO_NAME }}-nginx:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Сборка и публикация образа Frontend (builder) ---
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.REPO_NAME }}-frontend:latest
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.REPO_NAME }}-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
